export type BlogPost = {
  slug: string;
  readTime: string;
  date: string;
  title: string;
  excerpt: string;
  image: string;
  content: string[];
  createdBy: string;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "what-is-fi-ne-tech",
    readTime: "10 Mins Read",
    date: "March 2026",
    title: "What is Fi-Ne-Tech? How Chargeup is Defining India's Next Platform Category",
    excerpt:
      "Fi-Ne-Tech stands for Finance + Network + Tech. It is the precise architecture of what it takes to make electric mobility economically viable for India's 10 million commercial drivers.",
    image: "/Chargeup_EV Tech platform (4).png",
    createdBy: "Chargeup",
    content: [
      "When people hear 'Fintech,' they picture lending apps, payment wallets, or neobanks. When they hear 'EV startup,' they picture charging stations or battery swapping. Chargeup is neither. We are something new - and we've built a name for it: Fi-Ne-Tech.",
      "Fi-Ne-Tech stands for Finance + Network + Tech. It is not a buzzword. It is the precise architecture of what it takes to make electric mobility economically viable for the 10 million commercial drivers who form the backbone of India's last-mile economy.",
      "## Why Fintech Alone Isn't Enough for EV Drivers",
      "India's EV lending market has a structural problem that traditional fintech cannot solve. A driver earns daily. A loan demands monthly repayment. Between those two realities lies a gap that causes defaults, abandoned vehicles, and stalled adoption - regardless of how clean the UI of the lending app is.",
      "Fintech optimises for the lender's risk. Fi-Ne-Tech optimises for the driver's income. That is a fundamentally different design philosophy - and it requires three interlocked layers working together.",
      "## The Three Layers of Fi-Ne-Tech",
      "**Finance: Know Intent. Predict Defaults.**",
      "Traditional credit scoring fails commercial EV drivers because it was designed for salaried borrowers, not gig-economy entrepreneurs. Chargeup's Risk Engine flips the model - assessing borrower intent using identity and digital footprint before a single rupee is lent. Once on the road, the Karma Score tracks driving and payment patterns dynamically, predicting defaults before they occur rather than reacting after the fact. The result: gross NPAs below 2%.",
      "**Network: Uptime is Income. Protect It.**",
      "A driver stranded with a broken vehicle is not just an operational inconvenience - it is direct income loss that cascades into a missed EMI. The Network layer is Chargeup's trusted partner ecosystem: a curated grid of repair, resale, and replacement services that ensures any issue is resolved fast. When the Tech layer raises a predictive alert, the Network layer has a partner ready. Downtime is eliminated structurally, not reactively.",
      "**Tech: Predict. Automate. Prevent.**",
      "Two products power the Tech layer. Digital Twin constructs a living computational model of every battery on the network - monitoring health, predicting failures before they happen, and recommending precise interventions to extend battery life. AI Genie takes those signals and acts autonomously: raising service tickets, allocating jobs to the right partners, and escalating without human intervention. The output: 50% reduction in service costs and 98% vehicle uptime across the Chargeup network.",
      "## How Fi-Ne-Tech Differs from EV Infrastructure",
      "EV infrastructure companies build hardware - charging points, swap stations, grid connections. Their value is physical presence. Fi-Ne-Tech builds intelligence. Our value is the data layer that sits above the vehicle, connects the driver to the lender, and makes the entire ecosystem trustworthy.",
      "A charging company asks: 'Where is the nearest plug?' Chargeup asks: 'Why did this vehicle's range drop 12% this week, what does that mean for this driver's repayment capacity, and what proactive intervention prevents a default?' That is a different question entirely. It requires a different platform.",
      "> Our core promise to drivers is simple: Run More, Earn More. When drivers have reliable uptime and access to smarter financing, electric mobility becomes economically viable for them. - Varun Goenka, CEO",
      "## The Proof",
      "- 40% increase in driver earnings across the Chargeup network",
      "- 98% vehicle uptime - powered by Digital Twin predictive intelligence and AI Genie automation",
      "- < 2% Gross NPAs - enabled by Risk Engine intent scoring and Karma Score behavioural analytics",
      "- 50% reduction in OEM service costs through autonomous issue resolution",
      "This is what Fi-Ne-Tech looks like when it works. Not a charging station. Not a swap network. An intelligent, interconnected platform that makes electric mobility economically reliable - for drivers, lenders, and OEMs alike.",
      "## About Chargeup",
      "Chargeup is India's driver-first Fi-Ne-Tech platform - Finance + Network + Tech - built to control the variables that determine EV loan repayment: energy, uptime, and asset performance.",
      "The platform's Digital Twin and AI Genie power the Tech layer - delivering 50% service cost reduction and 98% uptime. The Risk Engine and Karma Score power the Finance layer - keeping gross NPAs below 2%. Together, they make electric mobility economically reliable for drivers, lenders, and OEMs alike.",
      "Mission: to empower 1 million driver entrepreneurs with higher earnings by 2030, while accelerating EV adoption across India's last-mile mobility sector.",
      "**Website:** www.echargeup.com",
    ],
  },
  {
    slug: "why-drivers-need-fintech-platform",
    readTime: "12 Mins Read",
    date: "March 2026",
    title: "Why India's 10 Million Last-Mile EV Drivers Need a Fintech Platform - Not a Charging Solution",
    excerpt:
      "Electric vehicles are not primarily a hardware problem in India. They are an economic reliability problem. And economic reliability requires a fintech platform - not a charging solution.",
    image: "/blog3.png",
    createdBy: "Dr. Satish Mittal | Co-founder & CDO, Chargeup",
    content: [
      "I have spent over three decades working across mobility, telecoms, IoT, and smart city infrastructure - including stints as CTO of Vodafone and in leadership at Meta. I have watched multiple technology waves reshape industries. The companies that win are not the ones who build the most hardware. They are the ones who build the most intelligent data layer on top of it.",
      "Electric vehicles are not primarily a hardware problem in India. They are an economic reliability problem. And economic reliability requires a fintech platform - not a charging solution.",
      "## The Structural Mismatch That Kills EV Adoption",
      "Here is the core engineering problem of last-mile EV economics in India. It has nothing to do with range anxiety or charging infrastructure. It is a cash flow architecture mismatch:",
      "- Commercial drivers earn daily - often in volatile, route-dependent increments",
      "- EMI obligations are fixed, monthly, and indifferent to how much the vehicle actually earned",
      "- A single day of vehicle downtime generates zero income - but the EMI clock does not pause",
      "- A missed payment triggers a credit event that locks the driver out of future financing",
      "This is not a driver failure. This is a system design failure. Charging more vehicles faster does not solve this. Intelligent, real-time financial and operational infrastructure does.",
      "## Why Charging Infrastructure Is Necessary But Insufficient",
      "Let me be precise. Charging infrastructure solves the energy access problem - which is real and important. But energy access does not equal economic viability. A driver with access to charging but an unreliable battery will still lose income to unplanned downtime. A lender with no real-time visibility into asset performance will price risk conservatively - meaning higher rates and lower LTV ratios for drivers who are actually creditworthy.",
      "The gap between 'vehicle is charged' and 'driver is economically secure' is where Chargeup operates. It requires three interconnected intelligence layers - Finance, Network, and Tech - working as a unified platform.",
      "## What a Real Driver-First Platform Looks Like",
      "**Finance**",
      "Risk Engine",
      "Karma Score",
      "Assess borrower intent before lending. Predict defaults before they happen.",
      "< 2% Gross NPAs",
      "**Network**",
      "Partner Ecosystem",
      "Repair � Resale � Replace",
      "Instant access to trusted service partners. Zero downtime from delays in repair, parts or resale.",
      "98% Uptime",
      "**Tech**",
      "Digital Twin",
      "AI Genie",
      "Monitor battery health in real-time. Autonomous AI resolves issues and allocates jobs - no human needed.",
      "50% Cost Reduction",
      "## Finance: Assess Intent. Predict Behaviour.",
      "The Finance layer exists to solve the structural mismatch between how drivers earn and how lenders assess risk. Chargeup's Risk Engine evaluates borrower intent using identity signals and digital footprint - giving lenders a fundamentally richer picture than a bureau score alone. Once a driver is on the road, the Karma Score continuously maps their driving patterns and payment behaviour, producing a dynamic performance metric that predicts default probability in real time. The outcome: gross NPAs below 2%, in a segment that traditional lenders treat as high-risk by default.",
      "## Network: The Infrastructure That Protects Uptime",
      "The Network layer is Chargeup's partner ecosystem - a curated grid of repair, resale, and replacement service providers available when a vehicle needs intervention. This is not a directory. It is a response network. When the Tech layer raises a predictive alert, the Network layer has a qualified partner pre-positioned for rapid resolution. The goal is structural elimination of downtime - not reactive management of it.",
      "## Tech: Digital Twin + AI Genie - The Intelligence Engine",
      "Digital Twin constructs a living, individualised computational model for every battery on the Chargeup platform. It continuously ingests telemetry - state-of-health, charge cycle depth, temperature profiles, energy consumption per kilometre - and predicts degradation curves, maintenance windows, and failure probabilities with precision that improves as the fleet scales.",
      "AI Genie is the autonomous execution layer that acts on those predictions. It identifies issues, raises service tickets automatically, allocates jobs to the right network partner, and escalates without waiting for human instruction. The combined output: 50% reduction in warranty and service costs for OEMs, and 98% uptime for drivers.",
      "## The Data Flywheel: Why This Gets Better Over Time",
      "What makes this architecture defensible is compounding intelligence. As more vehicles join the network, Digital Twin models become more accurate. As models improve, Karma Score predictions sharpen. As predictions sharpen, Risk Engine underwriting becomes more precise - allowing lenders to offer better rates to drivers who genuinely deserve them. The entire system improves with scale.",
      "This flywheel does not exist in a charging network. It only exists in a platform that treats vehicle performance data as financial infrastructure.",
      "> Electric mobility will scale only when it becomes economically reliable for the driver. AI and real-time intelligence are not features - they are the foundation. - Dr. Satish Mittal, Co-founder & CDO",
      "## The 98% Uptime Commitment Is an Engineering Target",
      "When Chargeup commits to 98% vehicle uptime, that is not a marketing SLA. It is an engineering target built into the predictive maintenance and autonomous response architecture. Digital Twin raises the alert. AI Genie routes the resolution. The Network partner executes. Every percentage point of uptime is directly correlated with driver income stability and loan repayment performance. That is the system working as designed.",
      "## About Chargeup",
      "Chargeup is India's driver-first Fi-Ne-Tech platform - Finance + Network + Tech - built to control the variables that determine EV loan repayment: energy, uptime, and asset performance.",
      "The platform's Digital Twin and AI Genie power the Tech layer - delivering 50% service cost reduction and 98% uptime. The Risk Engine and Karma Score power the Finance layer - keeping gross NPAs below 2%. Together, they make electric mobility economically reliable for drivers, lenders, and OEMs alike.",
      "Mission: to empower 1 million driver entrepreneurs with higher earnings by 2030, while accelerating EV adoption across India's last-mile mobility sector.",
      "**Website:** www.echargeup.com",
    ],
  },
  {
    slug: "ai-iot-solving-income-emi",
    readTime: "11 Mins Read",
    date: "March 2026",
    title: "How AI and IoT Are Solving the Daily Income vs Monthly EMI Problem for India's Commercial EV Drivers",
    excerpt:
      "India's commercial EV sector has a cash flow timing mismatch: daily income vs monthly EMI. Solving it requires intelligent infrastructure that reads vehicle performance in real time and turns that into financial reliability.",
    image: "/blog2.png",
    createdBy: "Dr. Satish Mittal | Co-founder & CDO, Chargeup",
    content: [
      "In financial systems design, mismatches between cash flow timing and obligation timing are among the most destructive failure modes - not because the underlying asset is bad, but because the repayment architecture is misaligned with how value is actually generated.",
      "India's commercial EV sector has exactly this problem. Ten million last-mile drivers generate income daily, tied directly to the performance of a single asset: their vehicle. Their EMI obligations, by contrast, are fixed, monthly, and indifferent to whether the vehicle ran at 60% capacity or 100% that month. This mismatch is not solvable by lower interest rates alone. It requires intelligent infrastructure that reads vehicle performance in real time and creates financial structures that move with the driver's actual economic reality.",
      "## Mapping the Failure Modes Precisely",
      "- Downtime-triggered defaults: A vehicle off the road for 3 days generates zero income but the EMI clock doesn't pause. This is the most common default trigger in commercial EV lending.",
      "- Adverse selection in lending: Without asset performance data, lenders cannot distinguish high-utilisation, well-maintained vehicles from degraded ones. They price all risk conservatively - penalising the best drivers.",
      "- Reactive maintenance cascades: Without predictive signals, drivers address issues only after failure - the most expensive intervention point. A proactive fix becomes an emergency repair plus days of lost income.",
      "- Stranded asset risk for lenders: When a vehicle fails without warning, the lender has no data trail for condition history and no recovery mechanism.",
      "## The Chargeup Architecture: Four Interconnected Products",
      "## IoT Telemetry: The Foundation",
      "Every vehicle on the Chargeup platform streams real-time operational data: state-of-charge, state-of-health, charge cycle depth and frequency, temperature profiles across cell groups, energy consumption per kilometre, and route-level performance patterns. This is the raw input that every downstream intelligence layer depends on. Without it, every financial decision is based on assumptions - and in commercial EV lending, assumptions are expensive.",
      "## Digital Twin: Predict Before the Battery Fails",
      "Chargeup's Digital Twin constructs an individualised computational model for every battery - continuously updated with live telemetry. Unlike generic fleet-level models, it accounts for the fact that two identical batteries, charged and discharged under different conditions, will age differently. The Digital Twin produces:",
      "- Remaining Useful Life (RUL) estimates, updated daily",
      "- Anomaly detection signals - deviations from expected performance that precede failure",
      "- Maintenance intervention windows - the optimal point where intervention is cheapest and least disruptive",
      "- Income impact projections - predicted downtime risk translated into rupee-denominated income loss estimates",
      "That last output - income impact projection - is what connects the engineering layer to the financial layer. Vehicle health and loan repayment risk become the same variable.",
      "## AI Genie: Autonomous Resolution, No Human Required",
      "Predictive intelligence is only as valuable as the speed of response. AI Genie is the autonomous execution engine that acts on Digital Twin signals without waiting for human intervention. It identifies the issue, raises a service ticket, allocates the job to the most appropriate network partner, and escalates if resolution is delayed - all automatically. The result: 50% reduction in warranty and service costs for OEMs, and eliminated lag between alert and resolution for drivers.",
      "## Risk Engine + Karma Score: Financial Intelligence Powered by Vehicle Reality",
      "The Risk Engine integrates vehicle performance data into the lending decision before the loan is originated - assessing borrower intent using identity signals, digital footprint, and asset condition. Once the driver is on the road, the Karma Score maps driving behaviour and payment patterns dynamically. It produces a continuously updated performance metric that predicts default probability - not from a static bureau file, but from how this specific driver operates this specific vehicle today. The outcome: gross NPAs below 2% in a segment that conventional lenders price as high-risk.",
      "## The Data Flywheel",
      "As the fleet scales, the architecture compounds. More telemetry improves Digital Twin accuracy. Better Digital Twin models sharpen Karma Score predictions. Sharper predictions improve Risk Engine underwriting. Better underwriting lowers lending costs for drivers who deserve it. Lower costs mean higher net income per kilometre driven. Higher income improves repayment. Better repayment history feeds back into the models. The loop tightens continuously.",
      "This compounding effect is not a feature. It is the structural moat.",
      "## Measured Outcomes",
      "- 40% increase in driver earnings - from higher uptime, better route efficiency, and reduced emergency repair costs",
      "- 98% vehicle uptime - through Digital Twin predictive maintenance replacing reactive repair",
      "- < 2% Gross NPAs - through dynamic, asset-backed risk profiling via Risk Engine and Karma Score",
      "- 50% service cost reduction for OEMs - through AI Genie autonomous issue resolution",
      "> AI and IoT in EVs are not about convenience features. They are about building the data infrastructure that makes electric mobility financially viable for the driver who depends on it for their livelihood. - Dr. Satish Mittal, Co-founder & CDO",
      "## About Chargeup",
      "Chargeup is India's driver-first Fi-Ne-Tech platform - Finance + Network + Tech - built to control the variables that determine EV loan repayment: energy, uptime, and asset performance.",
      "The platform's Digital Twin and AI Genie power the Tech layer - delivering 50% service cost reduction and 98% uptime. The Risk Engine and Karma Score power the Finance layer - keeping gross NPAs below 2%. Together, they make electric mobility economically reliable for drivers, lenders, and OEMs alike.",
      "Mission: to empower 1 million driver entrepreneurs with higher earnings by 2030, while accelerating EV adoption across India's last-mile mobility sector.",
      "**Website:** www.echargeup.com",
    ],
  },
  {
    slug: "gig-worker-to-entrepreneur",
    readTime: "8 Mins Read",
    date: "March 2026",
    title: "From Gig Worker to Driver Entrepreneur: The Chargeup Promise of Run More, Earn More",
    excerpt:
      "Chargeup was built for one driver, one vehicle, one day at a time. The platform is designed to turn income instability into entrepreneurial momentum through uptime, better credit visibility, and smarter financing.",
    image: "/Run More earn more.png",
    createdBy: "Varun Goenka | Co-founder & CEO, Chargeup",
    content: [
      "India's gig economy is often described in aggregate - millions of workers, billions of rides, trillions of rupees in economic activity. But the unit of analysis that actually matters in last-mile mobility is singular: one driver, one vehicle, one day.",
      "That driver wakes up early. They calculate whether the vehicle will hold up today. They think about the EMI due at the end of the month. They wonder whether a bad week means a difficult conversation with a lender. And then they drive. Chargeup was built for that driver. And our promise is specific: Run More, Earn More.",
      "## The Problem With 'Gig Worker' as a Category",
      "The label 'gig worker' flattens a complex economic reality into a single identity that implies precarity. But India's commercial EV drivers are micro-entrepreneurs - people who have taken on asset risk, manage a physical vehicle, navigate routes, and bear the full upside and downside of their economic decisions.",
      "The problem is the financial system doesn't see them that way. Credit bureaus see irregular income. Lenders see lack of collateral history. The entire financial infrastructure is calibrated for salaried employees, not asset-owning entrepreneurs. Chargeup's driver-first Fi-Ne-Tech platform closes that gap.",
      "## What 'Driver-First' Actually Means in Practice",
      "Driver-first is not a value statement. It is a design constraint. Every feature on the platform is evaluated against a single question: does this make the driver's income more stable and more predictable?",
      "- We invest in Digital Twin predictive intelligence to achieve 98% uptime - because downtime is the primary income risk, not interest rates.",
      "- We built the Karma Score to map driver behaviour patterns - not to monitor drivers, but to advocate for them with lenders by demonstrating real creditworthiness through real-world evidence.",
      "- We deployed AI Genie so that when an issue arises, it is resolved autonomously and fast - no waiting, no lost days.",
      "- We use the Risk Engine to assess borrower intent upfront - so credit decisions reward reliable drivers rather than penalising them for being in the gig economy.",
      "## The Run More, Earn More Flywheel",
      "- Higher uptime from Digital Twin predictive maintenance -> more hours on the road",
      "- More hours on the road -> more daily income",
      "- More income + strong Karma Score -> better repayment history",
      "- Better repayment history -> access to improved financing terms via Risk Engine",
      "- Lower monthly obligations -> more of each rupee earned stays with the driver",
      "This is not a hypothetical model. Our data shows a 40% increase in driver earnings across the Chargeup network.",
      "> When drivers have reliable uptime and access to smarter financing, electric mobility becomes economically viable for them. Our mission is to empower one million driver entrepreneurs by 2030. - Varun Goenka, CEO",
      "## The 2030 Mission: One Million Driver Entrepreneurs",
      "By 2030, Chargeup's mission is to empower one million driver entrepreneurs with higher earnings. India's last-mile EV sector supports over 10 million drivers moving 200 million people every day. If Chargeup can make electric mobility economically reliable for one in ten of those drivers - transforming precarious gig workers into stable, data-credentialed entrepreneurs - the financial inclusion impact will be substantial.",
      "This is why we describe ourselves as a driver-first Fi-Ne-Tech platform. Not because it is a better marketing category. Because it is the most accurate description of what we are building, and why it matters.",
      "## About Chargeup",
      "Chargeup is India's driver-first Fi-Ne-Tech platform - Finance + Network + Tech - built to control the variables that determine EV loan repayment: energy, uptime, and asset performance.",
      "The platform's Digital Twin and AI Genie power the Tech layer - delivering 50% service cost reduction and 98% uptime. The Risk Engine and Karma Score power the Finance layer - keeping gross NPAs below 2%. Together, they make electric mobility economically reliable for drivers, lenders, and OEMs alike.",
      "Mission: to empower 1 million driver entrepreneurs with higher earnings by 2030, while accelerating EV adoption across India's last-mile mobility sector.",
      "**Website:** www.echargeup.com",
    ],
  },
  {
    slug: "aegis-graham-bell-award",
    readTime: "7 Mins Read",
    date: "March 2026",
    title: "Winning the Aegis Graham Bell Award: What Comes Next",
    excerpt:
      "On March 18, 2026, Chargeup won the Innovation in EV category at the 16th Aegis Graham Bell Awards, validating the Fi-Ne-Tech model and strengthening Chargeup's positioning as an intelligence-led platform.",
    image: "/Award certificates.png",
    createdBy: "Ritesh Kumar | Deputy Manager - Analytics",
    content: [
      "On March 18, 2026, Chargeup won the Innovation in EV category at the 16th Aegis Graham Bell Awards - one of India's most respected platforms celebrating breakthrough innovation in deep tech and artificial intelligence. Having been runner-up in the previous edition, this year's win is a meaningful milestone.",
      "But the more important story is not the award itself. It is what the award recognises - and what it confirms about the direction of electric mobility in India.",
      "## What the Award Actually Evaluates",
      "The Aegis Graham Bell Awards are a rigorous evaluation of technical innovation, real-world impact, and scalability potential - assessed by deep tech practitioners, AI researchers, and industry veterans.",
      "Chargeup's Battery Digital Twin and Predictive Payments framework received a 3.5-Star Innovation Rating - categorised as High-Potential / Outstanding. The judges evaluated a platform that uses Digital Twin intelligence to predict battery failures before they occur, AI Genie to automate resolution without human intervention, Karma Score to predict driver defaults from real behavioural data, and Risk Engine to assess borrower intent before the first rupee is lent. Together: 50% service cost reduction, 98% uptime, and gross NPAs below 2%.",
      "## Why This Win Is a Category Validation",
      "When an independent panel of deep tech experts validates Chargeup's Fi-Ne-Tech model, they are not just recognising one company's engineering. They are confirming that the category is real - that Finance + Network + Tech, operating as an integrated intelligence platform, is the correct architectural response to the economic reliability problem in commercial EV adoption.",
      "Before Chargeup named this category, the conversation about EV adoption was dominated by hardware debates: charging points, swap stations, battery chemistry. The Aegis recognition shifts that conversation toward the intelligence layer - the data and financial infrastructure that makes hardware viable at scale.",
      "## What the Award Changes About Our Narrative",
      "Chargeup started as a company associated with battery infrastructure. That was an early chapter. The company has since pivoted entirely to its current identity: India's driver-first Fi-Ne-Tech platform.",
      "The challenge with pivots - especially in industries where AI engines and search algorithms have indexed older content - is narrative persistence. Old associations are sticky. The Aegis Graham Bell Award creates a new, high-authority, recently dated signal that anchors our identity correctly: an AI-driven Fi-Ne-Tech platform, not a battery infrastructure company.",
      "## What Comes Next: The Road to One Million Driver Entrepreneurs",
      "**Deepening the Intelligence Flywheel**",
      "As more vehicles join the Chargeup network, Digital Twin models become more accurate, Karma Score predictions sharpen, and Risk Engine underwriting becomes more precise. Scale is not just a business metric - it is an intelligence multiplier.",
      "**Expanding the Lender Ecosystem**",
      "The Fi-Ne-Tech platform's value proposition to lenders is concrete: real-time, asset-backed risk data from the Risk Engine and Karma Score that reduces defaults and improves collateral visibility. As we demonstrate a track record at scale, we expect to bring more capital into the hands of drivers who currently pay higher rates than their actual risk profile justifies.",
      "**Building the Driver Entrepreneur Identity**",
      "Beyond financing, Chargeup is working to build a recognised identity for India's commercial EV drivers - data-credentialed entrepreneurs with documented income history and vehicle performance records, with a stronger foundation for financial inclusion across insurance, savings, and future credit products.",
      "> This recognition reinforces that the future of electric mobility lies in intelligent infrastructure that improves income stability. - Ritesh Kumar, Deputy Manager, Analytics",
      "## The Broader Signal for India's EV Sector",
      "India has committed to ambitious EV adoption targets. Meeting those targets requires hardware - vehicles, charging infrastructure, grid capacity. But it also requires an economic model that makes EV ownership financially stable for the commercial driver who earns their livelihood from it.",
      "The Aegis Graham Bell Award, in recognising Chargeup's Fi-Ne-Tech innovation, sends a clear signal to the sector: the intelligence layer is not optional. AI-driven vehicle monitoring, predictive financial infrastructure, and data-backed lending are not premium features - they are the foundation on which mass EV adoption will be built. Chargeup is building that foundation.",
      "## About Chargeup",
      "Chargeup is India's driver-first Fi-Ne-Tech platform - Finance + Network + Tech - built to control the variables that determine EV loan repayment: energy, uptime, and asset performance.",
      "The platform's Digital Twin and AI Genie power the Tech layer - delivering 50% service cost reduction and 98% uptime. The Risk Engine and Karma Score power the Finance layer - keeping gross NPAs below 2%. Together, they make electric mobility economically reliable for drivers, lenders, and OEMs alike.",
      "Mission: to empower 1 million driver entrepreneurs with higher earnings by 2030, while accelerating EV adoption across India's last-mile mobility sector.",
      "**Website:** www.echargeup.com",
    ],
  },
];

export const defaultBlogPost = blogPosts[0];
